name: release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: asdf
        run: echo ${{ github.event.inputs.version }}
